/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaansmk.app;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Color;
import java.awt.color.ColorSpace;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import panels.CambiaPanel;

/**
 *
 * @author Ahmad
 */
public class Dashboard extends javax.swing.JFrame {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    /**
     * Creates new form p_Login
     */
    public Dashboard() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setResizable(false);
        setVisible(true);
        conn = koneksi.ConnectDb();
        new CambiaPanel(pnl_menu, new pnl_dashboard());
    }
    
        public void change_colorbtn(){
            btn_dashboard.setBackground(new Color(30,108,199));
            lbl_dashboard.setForeground(Color.WHITE);
            btn_peminjaman.setBackground(new Color(30,108,199));
            lbl_peminjaman.setForeground(Color.WHITE);
            btn_pengembalian.setBackground(new Color(30,108,199));
            lbl_pengembalian.setForeground(Color.WHITE);
            btn_databuku.setBackground(new Color(30,108,199));
            lbl_databuku.setForeground(Color.WHITE);
            btn_ebook.setBackground(new Color(30,108,199));
            lbl_ebook.setForeground(Color.WHITE);
            btn_anggota.setBackground(new Color(30,108,199));
            lbl_anggota.setForeground(Color.WHITE);
            btn_bukutamu.setBackground(new Color(30,108,199));
            lbl_bukutamu.setForeground(Color.WHITE);
        }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        side_menu = new javax.swing.JPanel();
        btn_anggota = new javax.swing.JPanel();
        lbl_anggota = new javax.swing.JLabel();
        lbl_dashboard6 = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JPanel();
        lbl_dashboard1 = new javax.swing.JLabel();
        lbl_dashboard = new javax.swing.JLabel();
        btn_peminjaman = new javax.swing.JPanel();
        lbl_peminjaman = new javax.swing.JLabel();
        lbl_dashboard2 = new javax.swing.JLabel();
        btn_databuku = new javax.swing.JPanel();
        lbl_databuku = new javax.swing.JLabel();
        lbl_dashboard4 = new javax.swing.JLabel();
        btn_ebook = new javax.swing.JPanel();
        lbl_ebook = new javax.swing.JLabel();
        lbl_dashboard5 = new javax.swing.JLabel();
        btn_pengembalian = new javax.swing.JPanel();
        lbl_pengembalian = new javax.swing.JLabel();
        lbl_dashboard3 = new javax.swing.JLabel();
        btn_bukutamu = new javax.swing.JPanel();
        lbl_bukutamu = new javax.swing.JLabel();
        lbl_dashboard7 = new javax.swing.JLabel();
        lbl_bukutamu1 = new javax.swing.JLabel();
        lbl_bukutamu2 = new javax.swing.JLabel();
        lbl_bukutamu3 = new javax.swing.JLabel();
        lbl_bukutamu4 = new javax.swing.JLabel();
        pnl_menu = new javax.swing.JPanel();
        pnl_menu1 = new javax.swing.JPanel();
        test = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Perpustakaan V 1.1.1");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        background.setBackground(new java.awt.Color(0, 0, 0));

        side_menu.setBackground(new java.awt.Color(30, 108, 199));
        side_menu.setMaximumSize(new java.awt.Dimension(270, 620));
        side_menu.setMinimumSize(new java.awt.Dimension(270, 620));
        side_menu.setPreferredSize(new java.awt.Dimension(270, 620));
        side_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_anggota.setBackground(new java.awt.Color(30, 108, 199));
        btn_anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_anggotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_anggotaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_anggotaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_anggotaMouseReleased(evt);
            }
        });

        lbl_anggota.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbl_anggota.setForeground(new java.awt.Color(255, 255, 255));
        lbl_anggota.setText("Data Anggota");

        lbl_dashboard6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbl_dashboard6.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dashboard6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/driver-license.png"))); // NOI18N

        javax.swing.GroupLayout btn_anggotaLayout = new javax.swing.GroupLayout(btn_anggota);
        btn_anggota.setLayout(btn_anggotaLayout);
        btn_anggotaLayout.setHorizontalGroup(
            btn_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_anggotaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbl_dashboard6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(lbl_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        btn_anggotaLayout.setVerticalGroup(
            btn_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lbl_dashboard6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        side_menu.add(btn_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 240, 40));

        btn_dashboard.setBackground(new java.awt.Color(250, 250, 250));
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_dashboardMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseReleased(evt);
            }
        });
        btn_dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_dashboard1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbl_dashboard1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dashboard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        btn_dashboard.add(lbl_dashboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        lbl_dashboard.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbl_dashboard.setText("Dashboard");
        btn_dashboard.add(lbl_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 150, 40));

        side_menu.add(btn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 40));

        btn_peminjaman.setBackground(new java.awt.Color(30, 108, 199));
        btn_peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_peminjamanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_peminjamanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_peminjamanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_peminjamanMouseReleased(evt);
            }
        });

        lbl_peminjaman.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbl_peminjaman.setForeground(new java.awt.Color(255, 255, 255));
        lbl_peminjaman.setText("Peminjaman Buku");

        lbl_dashboard2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbl_dashboard2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dashboard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/001-open-book.png"))); // NOI18N

        javax.swing.GroupLayout btn_peminjamanLayout = new javax.swing.GroupLayout(btn_peminjaman);
        btn_peminjaman.setLayout(btn_peminjamanLayout);
        btn_peminjamanLayout.setHorizontalGroup(
            btn_peminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_peminjamanLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_dashboard2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(lbl_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        btn_peminjamanLayout.setVerticalGroup(
            btn_peminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lbl_dashboard2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        side_menu.add(btn_peminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 240, 40));

        btn_databuku.setBackground(new java.awt.Color(30, 108, 199));
        btn_databuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_databukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_databukuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_databukuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_databukuMouseReleased(evt);
            }
        });

        lbl_databuku.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbl_databuku.setForeground(new java.awt.Color(255, 255, 255));
        lbl_databuku.setText("Data Buku");

        lbl_dashboard4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbl_dashboard4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dashboard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/003-book.png"))); // NOI18N

        javax.swing.GroupLayout btn_databukuLayout = new javax.swing.GroupLayout(btn_databuku);
        btn_databuku.setLayout(btn_databukuLayout);
        btn_databukuLayout.setHorizontalGroup(
            btn_databukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_databukuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbl_dashboard4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(lbl_databuku, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        btn_databukuLayout.setVerticalGroup(
            btn_databukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_databuku, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lbl_dashboard4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        side_menu.add(btn_databuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, -1));

        btn_ebook.setBackground(new java.awt.Color(30, 108, 199));
        btn_ebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ebookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ebookMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ebookMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_ebookMouseReleased(evt);
            }
        });

        lbl_ebook.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbl_ebook.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ebook.setText("Data E-Book");

        lbl_dashboard5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbl_dashboard5.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dashboard5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/005-book-1.png"))); // NOI18N

        javax.swing.GroupLayout btn_ebookLayout = new javax.swing.GroupLayout(btn_ebook);
        btn_ebook.setLayout(btn_ebookLayout);
        btn_ebookLayout.setHorizontalGroup(
            btn_ebookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ebookLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbl_dashboard5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(lbl_ebook, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        btn_ebookLayout.setVerticalGroup(
            btn_ebookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_ebook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_dashboard5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        side_menu.add(btn_ebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, -1));

        btn_pengembalian.setBackground(new java.awt.Color(30, 108, 199));
        btn_pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pengembalianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pengembalianMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_pengembalianMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_pengembalianMouseReleased(evt);
            }
        });

        lbl_pengembalian.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbl_pengembalian.setForeground(new java.awt.Color(255, 255, 255));
        lbl_pengembalian.setText("Pengembalian");

        lbl_dashboard3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbl_dashboard3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dashboard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/004-storytelling.png"))); // NOI18N

        javax.swing.GroupLayout btn_pengembalianLayout = new javax.swing.GroupLayout(btn_pengembalian);
        btn_pengembalian.setLayout(btn_pengembalianLayout);
        btn_pengembalianLayout.setHorizontalGroup(
            btn_pengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_pengembalianLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_dashboard3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(lbl_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        btn_pengembalianLayout.setVerticalGroup(
            btn_pengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lbl_dashboard3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        side_menu.add(btn_pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 240, 40));

        btn_bukutamu.setBackground(new java.awt.Color(30, 108, 199));
        btn_bukutamu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_bukutamuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_bukutamuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_bukutamuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_bukutamuMouseReleased(evt);
            }
        });

        lbl_bukutamu.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbl_bukutamu.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bukutamu.setText("Buku Pengunjung");

        lbl_dashboard7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbl_dashboard7.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dashboard7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/visitor.png"))); // NOI18N

        javax.swing.GroupLayout btn_bukutamuLayout = new javax.swing.GroupLayout(btn_bukutamu);
        btn_bukutamu.setLayout(btn_bukutamuLayout);
        btn_bukutamuLayout.setHorizontalGroup(
            btn_bukutamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_bukutamuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbl_dashboard7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(lbl_bukutamu, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        btn_bukutamuLayout.setVerticalGroup(
            btn_bukutamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_bukutamu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lbl_dashboard7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        side_menu.add(btn_bukutamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 240, -1));

        lbl_bukutamu1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbl_bukutamu1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bukutamu1.setText("SETTING");
        side_menu.add(lbl_bukutamu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        lbl_bukutamu2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbl_bukutamu2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bukutamu2.setText("MENU");
        side_menu.add(lbl_bukutamu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lbl_bukutamu3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbl_bukutamu3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bukutamu3.setText("CETAK");
        side_menu.add(lbl_bukutamu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        lbl_bukutamu4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbl_bukutamu4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bukutamu4.setText("LAPORAN");
        side_menu.add(lbl_bukutamu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        pnl_menu.setBackground(new java.awt.Color(255, 255, 255));
        pnl_menu.setMaximumSize(new java.awt.Dimension(910, 620));
        pnl_menu.setMinimumSize(new java.awt.Dimension(910, 620));
        pnl_menu.setPreferredSize(new java.awt.Dimension(910, 620));
        pnl_menu.setLayout(new javax.swing.BoxLayout(pnl_menu, javax.swing.BoxLayout.LINE_AXIS));

        pnl_menu1.setBackground(new java.awt.Color(61, 90, 128));
        pnl_menu1.setMaximumSize(new java.awt.Dimension(910, 620));
        pnl_menu1.setMinimumSize(new java.awt.Dimension(910, 620));
        pnl_menu1.setPreferredSize(new java.awt.Dimension(910, 620));
        pnl_menu1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        test.setForeground(new java.awt.Color(255, 255, 255));
        test.setText("Dashboard >");
        pnl_menu1.add(test, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 160, 40));

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(side_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
                    .addComponent(pnl_menu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(pnl_menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnl_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_menu.getAccessibleContext().setAccessibleName("");

        getContentPane().add(background);

        setSize(new java.awt.Dimension(1196, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_anggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anggotaMouseEntered
        // TODO add your handling code here:
        lbl_anggota.setForeground(Color.BLACK);
        btn_anggota.setBackground(new Color(250, 250, 250));
    }//GEN-LAST:event_btn_anggotaMouseEntered

    private void btn_anggotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anggotaMouseExited
        // TODO add your handling code here:
        if(test.getText().equals("Anggota > ")) {
            lbl_anggota.setForeground(Color.BLACK);
            btn_anggota.setBackground(new Color(250, 250, 250));
        } else {
            lbl_anggota.setForeground(Color.white);
            btn_anggota.setBackground(new Color(30,108,199));
        }
    }//GEN-LAST:event_btn_anggotaMouseExited

    private void btn_anggotaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anggotaMousePressed
        // TODO add your handling code here:
        change_colorbtn();
        lbl_anggota.setForeground(Color.BLACK);
        btn_anggota.setBackground(new Color(240, 240, 240));
        test.setText("Anggota > ");
        new CambiaPanel(pnl_menu, new pnl_anggota());
    }//GEN-LAST:event_btn_anggotaMousePressed

    private void btn_anggotaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anggotaMouseReleased
        lbl_anggota.setForeground(Color.BLACK);
        btn_anggota.setBackground(new Color(250, 250, 250));
    }//GEN-LAST:event_btn_anggotaMouseReleased

    private void btn_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseEntered
        // TODO add your handling code here:
        lbl_dashboard.setForeground(Color.BLACK);
        btn_dashboard.setBackground(new Color(250, 250, 250));
    }//GEN-LAST:event_btn_dashboardMouseEntered

    private void btn_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseExited
        // TODO add your handling code here:
        if(test.getText().equals("Dashboard > ")) {
            lbl_dashboard.setForeground(Color.BLACK);
            btn_dashboard.setBackground(new Color(250, 250, 250));
        } else {
            lbl_dashboard.setForeground(Color.white);
            btn_dashboard.setBackground(new Color(30,108,199));
        }
    }//GEN-LAST:event_btn_dashboardMouseExited

    private void btn_dashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMousePressed
        // TODO add your handling code here:
        change_colorbtn();
        lbl_dashboard.setForeground(Color.BLACK);
        btn_dashboard.setBackground(new Color(240, 240, 240));
        test.setText("Dashboard > ");
        new CambiaPanel(pnl_menu, new pnl_dashboard());
//        transaksi_buku.setFocusable(true);
    }//GEN-LAST:event_btn_dashboardMousePressed

    private void btn_dashboardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseReleased
        // TODO add your handling code here:
        lbl_dashboard.setForeground(Color.BLACK);
        btn_dashboard.setBackground(new Color(250, 250, 250));
    }//GEN-LAST:event_btn_dashboardMouseReleased

    private void btn_peminjamanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_peminjamanMouseEntered
        // TODO add your handling code here:
        lbl_peminjaman.setForeground(Color.BLACK);
        btn_peminjaman.setBackground(new Color(250, 250, 250));
    }//GEN-LAST:event_btn_peminjamanMouseEntered

    private void btn_peminjamanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_peminjamanMouseExited
        if(test.getText().equals("Peminjaman Buku > ")) {
            lbl_peminjaman.setForeground(Color.BLACK);
            btn_peminjaman.setBackground(new Color(250, 250, 250));
        } else {
            lbl_peminjaman.setForeground(Color.white);
            btn_peminjaman.setBackground(new Color(30,108,199));
        }
    }//GEN-LAST:event_btn_peminjamanMouseExited

    private void btn_peminjamanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_peminjamanMousePressed
        // TODO add your handling code here:
        change_colorbtn();
        lbl_peminjaman.setForeground(Color.BLACK);
        btn_peminjaman.setBackground(new Color(240, 240, 240));
        test.setText("Peminjaman Buku > ");
        new CambiaPanel(pnl_menu, new pnl_peminjaman());
    }//GEN-LAST:event_btn_peminjamanMousePressed

    private void btn_peminjamanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_peminjamanMouseReleased
        // TODO add your handling code here:
        lbl_peminjaman.setForeground(Color.BLACK);
        btn_peminjaman.setBackground(new Color(250, 250, 250));
    }//GEN-LAST:event_btn_peminjamanMouseReleased

    private void btn_databukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_databukuMouseEntered
        // TODO add your handling code here:
        lbl_databuku.setForeground(Color.BLACK);
        btn_databuku.setBackground(new Color(250, 250, 250));
    }//GEN-LAST:event_btn_databukuMouseEntered

    private void btn_databukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_databukuMouseExited
        if(test.getText().equals("Data Buku > ")) {
            lbl_databuku.setForeground(Color.BLACK);
            btn_databuku.setBackground(new Color(250, 250, 250));
        } else {
            lbl_databuku.setForeground(Color.white);
            btn_databuku.setBackground(new Color(30,108,199));
        }
    }//GEN-LAST:event_btn_databukuMouseExited

    private void btn_databukuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_databukuMousePressed
        // TODO add your handling code here:
        change_colorbtn();
        lbl_databuku.setForeground(Color.BLACK);
        btn_databuku.setBackground(new Color(240, 240, 240));
        test.setText("Data Buku > ");
        new CambiaPanel(pnl_menu, new pnl_databuku());
    }//GEN-LAST:event_btn_databukuMousePressed

    private void btn_databukuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_databukuMouseReleased
        lbl_databuku.setForeground(Color.BLACK);
        btn_databuku.setBackground(new Color(250, 250, 250));
    }//GEN-LAST:event_btn_databukuMouseReleased

    private void btn_ebookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ebookMouseEntered
        // TODO add your handling code here:
        lbl_ebook.setForeground(Color.BLACK);
        btn_ebook.setBackground(new Color(250, 250, 250));
    }//GEN-LAST:event_btn_ebookMouseEntered

    private void btn_ebookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ebookMouseExited
        if(test.getText().equals("Data E-Book > ")) {
            lbl_ebook.setForeground(Color.BLACK);
            btn_ebook.setBackground(new Color(250, 250, 250));
        } else {
            lbl_ebook.setForeground(Color.white);
            btn_ebook.setBackground(new Color(30,108,199));
        }
    }//GEN-LAST:event_btn_ebookMouseExited

    private void btn_ebookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ebookMousePressed
        // TODO add your handling code here:
        change_colorbtn();
        lbl_ebook.setForeground(Color.BLACK);
        btn_ebook.setBackground(new Color(240, 240, 240));
        test.setText("Data E-Book > ");
        new CambiaPanel(pnl_menu, new pnl_ebook());
    }//GEN-LAST:event_btn_ebookMousePressed

    private void btn_ebookMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ebookMouseReleased
        lbl_ebook.setForeground(Color.BLACK);
        btn_ebook.setBackground(new Color(250, 250, 250));
     }//GEN-LAST:event_btn_ebookMouseReleased

    private void btn_pengembalianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengembalianMouseEntered
        // TODO add your handling code here:
        lbl_pengembalian.setForeground(Color.BLACK);
        btn_pengembalian.setBackground(new Color(250, 250, 250));
    }//GEN-LAST:event_btn_pengembalianMouseEntered

    private void btn_pengembalianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengembalianMouseExited
        if(test.getText().equals("Pengembalian Buku > ")) {
            lbl_pengembalian.setForeground(Color.BLACK);
            btn_pengembalian.setBackground(new Color(250, 250, 250));
        } else {
            lbl_pengembalian.setForeground(Color.white);
            btn_pengembalian.setBackground(new Color(30,108,199));
        }
    }//GEN-LAST:event_btn_pengembalianMouseExited

    private void btn_pengembalianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengembalianMousePressed
        // TODO add your handling code here:
        change_colorbtn();
        lbl_pengembalian.setForeground(Color.BLACK);
        btn_pengembalian.setBackground(new Color(240, 240, 240));
        test.setText("Pengembalian Buku > ");
        new CambiaPanel(pnl_menu, new pnl_pengembalian());
    }//GEN-LAST:event_btn_pengembalianMousePressed

    private void btn_pengembalianMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengembalianMouseReleased
        lbl_pengembalian.setForeground(Color.BLACK);
        btn_pengembalian.setBackground(new Color(250, 250, 250));
     }//GEN-LAST:event_btn_pengembalianMouseReleased

    private void btn_bukutamuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bukutamuMouseEntered
        // TODO add your handling code here:
        lbl_bukutamu.setForeground(Color.BLACK);
        btn_bukutamu.setBackground(new Color(250, 250, 250));
    }//GEN-LAST:event_btn_bukutamuMouseEntered

    private void btn_bukutamuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bukutamuMouseExited
        if(test.getText().equals("Buku Tamu > ")) {
            lbl_bukutamu.setForeground(Color.BLACK);
            btn_bukutamu.setBackground(new Color(250, 250, 250));
        } else {
            lbl_bukutamu.setForeground(Color.white);
            btn_bukutamu.setBackground(new Color(30,108,199));
        }
    }//GEN-LAST:event_btn_bukutamuMouseExited

    private void btn_bukutamuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bukutamuMousePressed
        // TODO add your handling code here:
        change_colorbtn();
        lbl_bukutamu.setForeground(Color.BLACK);
        btn_bukutamu.setBackground(new Color(240, 240, 240));
        test.setText("Buku Tamu > ");
        new CambiaPanel(pnl_menu, new pnl_bukutamu());
    }//GEN-LAST:event_btn_bukutamuMousePressed

    private void btn_bukutamuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bukutamuMouseReleased
        lbl_bukutamu.setForeground(Color.BLACK);
        btn_bukutamu.setBackground(new Color(250, 250, 250));
     }//GEN-LAST:event_btn_bukutamuMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(p_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(p_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(p_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(p_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel btn_anggota;
    private javax.swing.JPanel btn_bukutamu;
    private javax.swing.JPanel btn_dashboard;
    private javax.swing.JPanel btn_databuku;
    private javax.swing.JPanel btn_ebook;
    private javax.swing.JPanel btn_peminjaman;
    private javax.swing.JPanel btn_pengembalian;
    private javax.swing.JLabel lbl_anggota;
    private javax.swing.JLabel lbl_bukutamu;
    private javax.swing.JLabel lbl_bukutamu1;
    private javax.swing.JLabel lbl_bukutamu2;
    private javax.swing.JLabel lbl_bukutamu3;
    private javax.swing.JLabel lbl_bukutamu4;
    private javax.swing.JLabel lbl_dashboard;
    private javax.swing.JLabel lbl_dashboard1;
    private javax.swing.JLabel lbl_dashboard2;
    private javax.swing.JLabel lbl_dashboard3;
    private javax.swing.JLabel lbl_dashboard4;
    private javax.swing.JLabel lbl_dashboard5;
    private javax.swing.JLabel lbl_dashboard6;
    private javax.swing.JLabel lbl_dashboard7;
    private javax.swing.JLabel lbl_databuku;
    private javax.swing.JLabel lbl_ebook;
    private javax.swing.JLabel lbl_peminjaman;
    private javax.swing.JLabel lbl_pengembalian;
    private javax.swing.JPanel pnl_menu;
    private javax.swing.JPanel pnl_menu1;
    private javax.swing.JPanel side_menu;
    private javax.swing.JLabel test;
    // End of variables declaration//GEN-END:variables
}
