/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaansmk.app;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahmad
 */
public class loading extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    /**
     * Creates new form loading
     */
    public loading() {
        initComponents();
        setUndecorated(true);
        autoclose();
    }

    private void autoclose(){
            new java.util.Timer().schedule(
            new java.util.TimerTask() {
                @Override
                public void run() {
                    tablesiswa();
                    setVisible(false);
                }
            },
            3000
        );
    }
    
    private DefaultTableModel tabmode;
    pnl_databuku databuku = new pnl_databuku();
    public void tablesiswa(){
    conn=koneksi.ConnectDb();
//        id	judul_buku	pengarang	penerbit	tahun_terbit	kode_ISBN_13	kode_ISBN_10	jumlah	harga	lokasi_rak	foto_cover	ringkasan	tanggal
    Object[] Baris = {"ID","Cover Buku","Judul Buku","Lokasi Rak","Pengarang","Penerbit","Tahun Terbit","ISBN-13","ISBN-10","Jumlah Buku", "Harga Buku",  "Ringkasan","Tanggal"};
    tabmode = new DefaultTableModel(null, Baris);
    databuku.tb_buku.setModel(tabmode);
    String sql = "select * from `tb_databuku`";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("id");
                String b = hasil.getString("foto_cover");
                String c = hasil.getString("judul_buku");
                String d = hasil.getString("lokasi_rak");
                String e = hasil.getString("pengarang");
                String f = hasil.getString("penerbit");
                String g = hasil.getString("tahun_terbit");
                String h = hasil.getString("kode_ISBN_13");
                String i = hasil.getString("kode_ISBN_10");
                String j = hasil.getString("jumlah");
                String k = hasil.getString("harga");
                String l = hasil.getString("ringkasan");
                String m = hasil.getString("tanggal");
                
                String[] data ={a,b,c,d,e,f,g,h,i,j,k,l,m};
                tabmode.addRow(data);
            }
        } catch (Exception e) { 
            
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(880, 440));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/giphy.gif"))); // NOI18N
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);

        setSize(new java.awt.Dimension(880, 440));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
