/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaansmk.app;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author Ahmad
 */
public class transaksi_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form tambah_buku
     */
    public transaksi_dashboard() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id_buku = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pengembalian = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbl_pengembalian = new javax.swing.JLabel();
        lihat_data = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbl_lihat_data = new javax.swing.JLabel();
        buku_rusak = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbl_buku_rusak = new javax.swing.JLabel();
        peminjaman = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_peminjaman = new javax.swing.JLabel();
        tambah_buku = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbl_tambah_buku = new javax.swing.JLabel();
        peminjaman1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbl_peminjaman1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(30, 108, 199));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Transaksi Buku");

        id_buku.setEditable(false);
        id_buku.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        id_buku.setText("12341414141");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID BUKU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 443, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(id_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(id_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        pengembalian.setBackground(new java.awt.Color(42, 157, 143));
        pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pengembalianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pengembalianMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/completed-task.png"))); // NOI18N

        lbl_pengembalian.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbl_pengembalian.setForeground(new java.awt.Color(255, 255, 255));
        lbl_pengembalian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_pengembalian.setText("Pengembalian");

        javax.swing.GroupLayout pengembalianLayout = new javax.swing.GroupLayout(pengembalian);
        pengembalian.setLayout(pengembalianLayout);
        pengembalianLayout.setHorizontalGroup(
            pengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengembalianLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addContainerGap(52, Short.MAX_VALUE))
            .addComponent(lbl_pengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pengembalianLayout.setVerticalGroup(
            pengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengembalianLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lbl_pengembalian)
                .addGap(24, 24, 24))
        );

        jPanel1.add(pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 160, 160));

        lihat_data.setBackground(new java.awt.Color(244, 162, 97));
        lihat_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lihat_dataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lihat_dataMouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/folder.png"))); // NOI18N

        lbl_lihat_data.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbl_lihat_data.setForeground(new java.awt.Color(255, 255, 255));
        lbl_lihat_data.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_lihat_data.setText("Lihat Data Buku");

        javax.swing.GroupLayout lihat_dataLayout = new javax.swing.GroupLayout(lihat_data);
        lihat_data.setLayout(lihat_dataLayout);
        lihat_dataLayout.setHorizontalGroup(
            lihat_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lihat_dataLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel6)
                .addContainerGap(52, Short.MAX_VALUE))
            .addComponent(lbl_lihat_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        lihat_dataLayout.setVerticalGroup(
            lihat_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lihat_dataLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(lbl_lihat_data)
                .addGap(22, 22, 22))
        );

        jPanel1.add(lihat_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 160, 160));

        buku_rusak.setBackground(new java.awt.Color(231, 111, 81));
        buku_rusak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buku_rusakMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buku_rusakMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delivery-box.png"))); // NOI18N

        lbl_buku_rusak.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbl_buku_rusak.setForeground(new java.awt.Color(255, 255, 255));
        lbl_buku_rusak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_buku_rusak.setText("Buku Rusak");

        javax.swing.GroupLayout buku_rusakLayout = new javax.swing.GroupLayout(buku_rusak);
        buku_rusak.setLayout(buku_rusakLayout);
        buku_rusakLayout.setHorizontalGroup(
            buku_rusakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buku_rusakLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel5)
                .addContainerGap(52, Short.MAX_VALUE))
            .addComponent(lbl_buku_rusak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        buku_rusakLayout.setVerticalGroup(
            buku_rusakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buku_rusakLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(lbl_buku_rusak)
                .addGap(25, 25, 25))
        );

        jPanel1.add(buku_rusak, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, -1));

        peminjaman.setBackground(new java.awt.Color(38, 70, 83));
        peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                peminjamanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                peminjamanMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/teamwork.png"))); // NOI18N

        lbl_peminjaman.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbl_peminjaman.setForeground(new java.awt.Color(255, 255, 255));
        lbl_peminjaman.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_peminjaman.setText("Pengunjung");

        javax.swing.GroupLayout peminjamanLayout = new javax.swing.GroupLayout(peminjaman);
        peminjaman.setLayout(peminjamanLayout);
        peminjamanLayout.setHorizontalGroup(
            peminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peminjamanLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addContainerGap(52, Short.MAX_VALUE))
            .addComponent(lbl_peminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        peminjamanLayout.setVerticalGroup(
            peminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peminjamanLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(lbl_peminjaman)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(peminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 160, 160));

        tambah_buku.setBackground(new java.awt.Color(233, 196, 106));
        tambah_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tambah_bukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tambah_bukuMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/book.png.png"))); // NOI18N

        lbl_tambah_buku.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbl_tambah_buku.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tambah_buku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tambah_buku.setText("Tambah Buku");

        javax.swing.GroupLayout tambah_bukuLayout = new javax.swing.GroupLayout(tambah_buku);
        tambah_buku.setLayout(tambah_bukuLayout);
        tambah_bukuLayout.setHorizontalGroup(
            tambah_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambah_bukuLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel7)
                .addContainerGap(52, Short.MAX_VALUE))
            .addComponent(lbl_tambah_buku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tambah_bukuLayout.setVerticalGroup(
            tambah_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambah_bukuLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(lbl_tambah_buku)
                .addGap(22, 22, 22))
        );

        jPanel1.add(tambah_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        peminjaman1.setBackground(new java.awt.Color(38, 70, 83));
        peminjaman1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                peminjaman1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                peminjaman1MouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/borrow book.png"))); // NOI18N

        lbl_peminjaman1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbl_peminjaman1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_peminjaman1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_peminjaman1.setText("Peminjaman");

        javax.swing.GroupLayout peminjaman1Layout = new javax.swing.GroupLayout(peminjaman1);
        peminjaman1.setLayout(peminjaman1Layout);
        peminjaman1Layout.setHorizontalGroup(
            peminjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peminjaman1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel9)
                .addContainerGap(52, Short.MAX_VALUE))
            .addComponent(lbl_peminjaman1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        peminjaman1Layout.setVerticalGroup(
            peminjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peminjaman1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addGap(26, 26, 26)
                .addComponent(lbl_peminjaman1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(peminjaman1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 160, 160));

        getContentPane().add(jPanel1);

        setSize(new java.awt.Dimension(878, 565));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void peminjamanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peminjamanMouseEntered
        // TODO add your handling code here:
        lbl_peminjaman.setForeground(Color.white);
        peminjaman.setBackground(new Color(30,108,199));
    }//GEN-LAST:event_peminjamanMouseEntered

    private void peminjamanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peminjamanMouseExited
        lbl_peminjaman.setForeground(Color.white);
        peminjaman.setBackground(new Color(38,70,83));
    }//GEN-LAST:event_peminjamanMouseExited

    private void pengembalianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengembalianMouseEntered
        lbl_pengembalian.setForeground(Color.white);
        pengembalian.setBackground(new Color(30,108,199));
    }//GEN-LAST:event_pengembalianMouseEntered

    private void pengembalianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengembalianMouseExited
        lbl_pengembalian.setForeground(Color.white);
        pengembalian.setBackground(new Color(42,157,143));
    }//GEN-LAST:event_pengembalianMouseExited

    private void buku_rusakMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buku_rusakMouseEntered
        lbl_buku_rusak.setForeground(Color.white);
        buku_rusak.setBackground(new Color(30,108,199));
    }//GEN-LAST:event_buku_rusakMouseEntered

    private void buku_rusakMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buku_rusakMouseExited
        lbl_buku_rusak.setForeground(Color.white);
        buku_rusak.setBackground(new Color(231,111,81));
    }//GEN-LAST:event_buku_rusakMouseExited

    private void lihat_dataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lihat_dataMouseEntered
        lbl_lihat_data.setForeground(Color.white);
        lihat_data.setBackground(new Color(30,108,199));
    }//GEN-LAST:event_lihat_dataMouseEntered

    private void lihat_dataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lihat_dataMouseExited
        lbl_lihat_data.setForeground(Color.white);
        lihat_data.setBackground(new Color(244,162,97));
    }//GEN-LAST:event_lihat_dataMouseExited

    private void tambah_bukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah_bukuMouseEntered
        lbl_tambah_buku.setForeground(Color.white);
        tambah_buku.setBackground(new Color(30,108,199));
    }//GEN-LAST:event_tambah_bukuMouseEntered

    private void tambah_bukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah_bukuMouseExited
        lbl_tambah_buku.setForeground(Color.white);
        tambah_buku.setBackground(new Color(233,196,106));
    }//GEN-LAST:event_tambah_bukuMouseExited

    private void peminjaman1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peminjaman1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_peminjaman1MouseEntered

    private void peminjaman1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peminjaman1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_peminjaman1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }

//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(tambah_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(tambah_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(tambah_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(tambah_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buku_rusak;
    private javax.swing.JTextField id_buku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_buku_rusak;
    private javax.swing.JLabel lbl_lihat_data;
    private javax.swing.JLabel lbl_peminjaman;
    private javax.swing.JLabel lbl_peminjaman1;
    private javax.swing.JLabel lbl_pengembalian;
    private javax.swing.JLabel lbl_tambah_buku;
    private javax.swing.JPanel lihat_data;
    private javax.swing.JPanel peminjaman;
    private javax.swing.JPanel peminjaman1;
    private javax.swing.JPanel pengembalian;
    private javax.swing.JPanel tambah_buku;
    // End of variables declaration//GEN-END:variables
}
